# Generated by Django 2.2 on 2019-04-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usuario',
        ),
    ]
