# Generated by Django 2.2 on 2019-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190410_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=150, unique=True)),
                ('Asiento', models.IntegerField(default='0')),
                ('Hora_Salida', models.DateField()),
                ('Fecha_Salida', models.TimeField()),
            ],
        ),
    ]
