# Generated by Django 2.2 on 2019-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pasaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
