# Generated by Django 2.2 on 2019-04-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190412_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rut',
        ),
    ]
