# Generated by Django 2.2 on 2019-04-12 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='Dueño',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
