# Generated by Django 2.2 on 2019-04-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pasaje_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='Fecha_Salida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='Hora_Salida',
            field=models.TimeField(),
        ),
    ]
