# Generated by Django 2.2 on 2019-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
