# Generated by Django 2.2 on 2019-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='edad',
            field=models.IntegerField(default='0'),
        ),
    ]
