# Generated by Django 2.2 on 2019-04-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0015_remove_administrador_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
