# Generated by Django 2.2 on 2019-04-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_pasaje_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasaje',
            name='test',
        ),
    ]
