# Generated by Django 2.2 on 2019-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_pasaje_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='Valoracion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default='0'),
        ),
    ]
