# Generated by Django 2.2 on 2019-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pasaje_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='Valoracion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0'),
        ),
    ]
