# Generated by Django 2.2 on 2019-04-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
        ('users', '0021_auto_20190416_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='PatenteBus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Buses.Bus'),
            preserve_default=False,
        ),
    ]
