# Generated by Django 2.2 on 2019-04-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190416_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patente', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pasaje',
            name='PatenteBus',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='users.Bus'),
            preserve_default=False,
        ),
    ]
