# Generated by Django 2.2 on 2019-04-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190417_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='PatenteBus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buses.Bus'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
