# Generated by Django 2.2 on 2019-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_pasaje_patentebus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
