# Generated by Django 2.2 on 2019-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190419_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='Dueño',
            field=models.CharField(max_length=150),
        ),
    ]
