# Generated by Django 2.2 on 2019-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190420_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='Valoracion',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0'),
        ),
    ]
