# Generated by Django 2.2 on 2019-05-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190423_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='Valor',
            field=models.IntegerField(default='0'),
        ),
    ]
