# Generated by Django 2.2 on 2019-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorSubastaActualizado', models.IntegerField(default='0')),
                ('Puja', models.IntegerField(default='0')),
                ('HoraI_Subasta', models.TimeField()),
                ('HoraF_Subasta', models.TimeField()),
                ('Fecha_Subasta', models.DateField()),
                ('Estado_Subasta', models.BooleanField(default=False)),
                ('Estado_Puja', models.BooleanField(default=False)),
            ],
        ),
    ]
