# Generated by Django 2.2 on 2019-05-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0005_subasta_ultima_puja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='Ultima_Puja',
        ),
    ]
