# Generated by Django 2.2 on 2019-05-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190423_1451'),
        ('subasta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorSubastaActualizado', models.IntegerField(default='0')),
                ('Puja', models.IntegerField(default='0')),
                ('HoraI_Subasta', models.TimeField()),
                ('HoraF_Subasta', models.TimeField()),
                ('Fecha_Subasta', models.DateField()),
                ('Estado_Subasta', models.BooleanField(default=False)),
                ('Estado_Puja', models.BooleanField(default=False)),
                ('Pasaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Pasaje')),
            ],
        ),
        migrations.DeleteModel(
            name='Pasaje',
        ),
    ]
