# Generated by Django 2.2 on 2019-05-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0002_auto_20190514_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='Pasaje',
        ),
    ]
