# Generated by Django 2.2 on 2019-05-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190423_1451'),
        ('subasta', '0003_remove_subasta_pasaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='Pasaje_A_Sub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Pasaje'),
            preserve_default=False,
        ),
    ]
