# Generated by Django 2.2 on 2019-05-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subasta', '0004_subasta_pasaje_a_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='Ultima_Puja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
